# Generated by Django 2.1.4 on 2019-01-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='note',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
