# Generated by Django 2.1.4 on 2019-01-19 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_app', '0002_auto_20190119_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticsnotes',
            name='profile',
        ),
        migrations.DeleteModel(
            name='StatisticsNotes',
        ),
    ]
