# Generated by Django 2.1.4 on 2019-01-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(related_name='_profile_subscriptions_+', to='Profile.Profile'),
        ),
    ]
