# Generated by Django 2.1.4 on 2019-01-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_profile_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subscriptions',
        ),
    ]
