# Generated by Django 2.1.4 on 2019-01-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_remove_profile_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(related_name='Subscriptions', to='Profile.Profile'),
        ),
    ]
